### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by bcbeatty** [trifork/hapi-fhir-jpaserver-starter#13]
I cloned the repo and I attempt to run the following commands
mvn jetty:run or mvn clean spring-boot:run -Pboot~

I'm getting the following response
`
[INFO] Scanning for projects...
Downloading from oss-snapshots: https://oss.sonatype.org/content/repositories/snapshots/ca/uhn/hapi/fhir/hapi-fhir/7.2.1/hapi-fhir-7.2.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/ca/uhn/hapi/fhir/hapi-fhir/7.2.1/hapi-fhir-7.2.1.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for ca.uhn.hapi.fhir:hapi-fhir-jpaserver-starter:7.2.1: The following artifacts could not be resolved: ca.uhn.hapi.fhir:hapi-fhir:pom:7.2.1 (absent): Could not transfer artifact ca.uhn.hapi.fhir:hapi-fhir:pom:7.2.1 from/to oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and 'parent.relativePath' points at wrong local POM @ line 14, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project ca.uhn.hapi.fhir:hapi-fhir-jpaserver-starter:7.2.1 (C:\Code\hapi-fhir-jpaserver-starter\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for ca.uhn.hapi.fhir:hapi-fhir-jpaserver-starter:7.2.1: The following artifacts could not be resolved: ca.uhn.hapi.fhir:hapi-fhir:pom:7.2.1 (absent): Could not transfer artifact ca.uhn.hapi.fhir:hapi-fhir:pom:7.2.1 from/to oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and 'parent.relativePath' points at wrong local POM @ line 14, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

`

Any suggestions on how to resolve this issue?

**Comment by XcrigX** [comment]
That looks like a TLS issue. Perhaps it's transient?  Or the machine you are running on (or your JVM) doesn't trust a certificate (likely from https://oss.sonatype.org) 

FWIW, I tested myself with this and was able to clone and run: 
mvn clean package spring-boot:repackage -DskipTests=true -Pboot && java -jar target/ROOT.war

Also, did you intend to clone this fork of the project (trifork) and not the main project?

**Comment by bcbeatty** [comment]
How do I resolve the TLS issue? I have a pretty new machine.

**Comment by XcrigX** [comment]
It's hard to say. But this error "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path" - almost always points to a bad TLS certificate, or problem with the truststore trying to validate the certificate chain. 
You generally have two trust stores in play - the one that Windows maintains, and the Java VM has it's own truststore that is created when you download/install java. I'm not 100% sure which one is in play here. 

First thing is I would do is just try it again in case it was a transient error on the server side. I would try it in two steps also (build and then run). 
s1: build
mvn clean package spring-boot:repackage -DskipTests=true

s2: run
java -jar target/ROOT.war

If it still fails, see if you can reach this link from a browser without it flagging a bad TLS cert: https://oss.sonatype.org/  - I'm not positive that's the site it had a problem with, but it was in the log and would make sense if it's trying to download dependencies from there. 

If you can't reach that site without your browser complaining - it's  a windows truststore problem (or an actual problem with https://oss.sonatype.org. Or it could be whatever firewalls, etc. you have to pass through could be blocking something. 

The other thing you could try is updating Java, but I'd be surprised if that is the problem, TBH.

**Comment by XcrigX** [comment]
.. also, just to restate - this is a private fork of the HAPI project where you've logged this issue. I'm not sure if that was intentional or not. The public project is here: 
https://github.com/hapifhir/hapi-fhir-jpaserver-starter

**Comment by bcbeatty** [comment]
thanks for the help, I'll check the main project
